hello:
  msg: ass

es:
  host: 127.0.0.1
  username: test
  password: 123
  port: 6379
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: asdada
  accessKeySecret: dadadadad
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false
    #url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.hxd.aoptest.model
  mapper-locations: classpath:mapping/*Mapper.xml